name: Vibely Service Pipeline

on:
  push:
    branches:
      - staging

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build-test
    environment: staging

    steps:
      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ vars.SERVER_KEY }}
        run: |
          mkdir -p ~/key
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/key/mykey.pem
          chmod 600 ~/key/mykey.pem

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./build

      - name: Run deployment 
        env:
          ENV_FILE: ${{ vars.ENV_FILE }}
        run: |
          echo "$ENV_FILE" > /tmp/env_content

          echo "Current directory:"
          pwd

          echo "List root:"
          ls -la

          echo "List build folder:"
          ls -la build

          scp -i ~/key/mykey.pem -o StrictHostKeyChecking=no /tmp/env_content ec2-user@api.truewaysindia.com:/tmp/.env.tmp

          scp -r -i ~/key/mykey.pem -o StrictHostKeyChecking=no ./build/dist ec2-user@api.truewaysindia.com:/tmp/dist/

          ssh -i ~/key/mykey.pem -o StrictHostKeyChecking=no ec2-user@api.truewaysindia.com << 'EOF'

            echo "Current directory check:"
            pwd
            
            echo "Source Bash"
            source ~/.bashrc

            echo "Changing directory..."
            cd Desktop/vibely/backend/Vibely-Backend

            echo "Checking pwd:"
            pwd

            echo "Removing Old Dist"
            rm -r dist

            echo "Copy dist"
            cp -r /tmp/dist/* ./

            echo "Going to dist"
            cd dist

            echo "Moving .env file from tmp"
            mv /tmp/.env.tmp .env

            echo "Installing dependencies..."
            npm i

            echo "Reloading PM2..."
            npx pm2 reload vibely
          EOF
